version: '3'
services:
    api:
        build: ./api
        volumes:
            - ./api:/go/src/api
        ports:
            - 8090:8090
    web:
        build: ./web
        volumes:
            - ./web:/app
        environment:
          - npm_config_unsafe_perm=true
        ports:
            - 8080:8080
